-- EMS baseline schema (PostgreSQL)
-- Owned by Flyway; Hibernate runs with ddl-auto=validate against this schema.

CREATE TABLE roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR(50)  NOT NULL UNIQUE,
    email             VARCHAR(100) NOT NULL UNIQUE,
    password          VARCHAR(100) NOT NULL,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP,
    created_by        VARCHAR(50),
    last_modified_by  VARCHAR(50),
    version           BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE departments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(80)  NOT NULL UNIQUE,
    code              VARCHAR(10)  NOT NULL UNIQUE,
    location          VARCHAR(100),
    description       VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL,
    updated_at        TIMESTAMP,
    created_by        VARCHAR(50),
    last_modified_by  VARCHAR(50),
    version           BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE employees (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code     VARCHAR(15)   NOT NULL UNIQUE,
    first_name        VARCHAR(50)   NOT NULL,
    last_name         VARCHAR(50)   NOT NULL,
    email             VARCHAR(100)  NOT NULL UNIQUE,
    phone             VARCHAR(20),
    job_title         VARCHAR(80)   NOT NULL,
    salary            NUMERIC(12,2) NOT NULL,
    hire_date         DATE          NOT NULL,
    status            VARCHAR(20)   NOT NULL,
    department_id     BIGINT        NOT NULL REFERENCES departments (id),
    user_id           BIGINT        UNIQUE REFERENCES users (id) ON DELETE SET NULL,
    created_at        TIMESTAMP     NOT NULL,
    updated_at        TIMESTAMP,
    created_by        VARCHAR(50),
    last_modified_by  VARCHAR(50),
    version           BIGINT        NOT NULL DEFAULT 0
);

CREATE INDEX idx_employees_department ON employees (department_id);
CREATE INDEX idx_employees_status     ON employees (status);
CREATE INDEX idx_employees_hire_date  ON employees (hire_date);
CREATE INDEX idx_user_roles_role      ON user_roles (role_id);
